---
commitizen:
  major_version_zero: true
  name: cz_conventional_commits
  annotated_tag: true
  tag_format: $version
  update_changelog_on_bump: true
  version_provider: npm
  version_scheme: semver
  version_files:
    - Makefile:VERSION
